### ISSUE TITLE
UI Improvisation of Home Page, EditText 

### ISSUE THREAD

**Issue by jazxii** [IEEE-VIT/weatherbes-android#11]

**Comment by vishal206** [comment]
I would like to work on it

**Comment by jazxii** [comment]
Hi @vishal206 . You could improve the background of the home page maybe make it look better?
As for the edit text and buttons, you can make try material.io components and make them look presentable?
We will be assigning you. Good Luck!

**Comment by vishal206** [comment]
@jazxii I have made my PR, could you pls check that!
