### ISSUE TITLE
Add live suggestions

### ISSUE THREAD

**Issue by Jatin887** [IEEE-VIT/weatherbes-android#14]
Auto complete feature

**Comment by vishal206** [comment]
Hi, Can you assign me for this issue I would like to work on this issue?

**Comment by Archita01** [comment]
Hi @vishal206 i have assigned the issue to you. Good luck :)

**Comment by vishal206** [comment]
In this issue, by the live suggestion they mean when the user types city name it should give some list of suggestions ri8!

**Comment by Archita01** [comment]
yes, we can autocomplete the name of the city entered by the user.

**Comment by vishal206** [comment]
> yes, we can autocomplete the name of the city entered by the user.
Thank you.

**Comment by Bhavik0902** [comment]
Where should i check which one is assigned and which one is not to the participant?

**Comment by Bhavik0902** [comment]
Whether this issue is assigned and solved?

**Comment by Archita01** [comment]
There will be an assigned notification in the comments section. You can also refer to the assignes column.
![477D04E6-1A1D-4E8D-9902-66C2D84ADD9D](https://user-images.githubusercontent.com/79601359/135729157-5a2a7bfd-6525-4737-802e-d56d10cce544.jpeg)

**Comment by Archita01** [comment]
@Bhavik0902 If an issue is closed, it means that it has been solved already.

**Comment by vishal206** [comment]
Hey, I figured out who to have a live suggestion dropdown and collected cities data for it. 
I'm facing some problem with connecting the CSV file, when it's done I will give a PR @Archita01

**Comment by Archita01** [comment]
Cool, no problem @vishal206

**Comment by jazxii** [comment]
The previous PR was reverted as build Failed. @vishal206 pls work on the fix and make a new PR.
@Ishan-001 pls check

**Comment by vishal206** [comment]
sure bro I will work on it. @jazxii

**Comment by vishal206** [comment]
I have made a new PR
> The previous PR was reverted as build Failed. @vishal206 pls work on the fix and make a new PR. @Ishan-001 pls check
