### ISSUE TITLE
application is crashing

### ISSUE THREAD

**Issue by vilgad** [IEEE-VIT/weatherbes-android#22]
when i installed this application using android studio then ut shows the "Enter city" screen and after pressing go it starts loading and crashes after 6 seconds

**Comment by Jatin887** [comment]
@vilgad do you waana solve this ?

**Comment by Jatin887** [comment]
@vilgad you have to generate a alert like 'This field can't be empty'

**Comment by iamyajat** [comment]
Hey @Jatin887, can I pick this issue up?

**Comment by jazxii** [comment]
yes

**Comment by iamyajat** [comment]
@jazxii I have fixed the issue!

**Comment by jazxii** [comment]
Hey @iamyajat! Congratulations on getting the first PR merged, we would like to give you a shoutout on our twitter account twitter.com/ieeevitvellore. Can you please provide us with your twitter handle?
