### ISSUE TITLE
Animated Splash Screen

### ISSUE THREAD

**Issue by Kajal13081** [IEEE-VIT/weatherbes-android#29]
I want to make the splash screen animated. Can you assign me this?

**Comment by Archita01** [comment]
Sure! I have assigned the issue to you @Kajal13081. All the best :)

**Comment by namra4122** [comment]
I am working on an animation splash screen can u please assign me this??

**Comment by Kajal13081** [comment]
#45 
issue fixed @Archita01

**Comment by Jatin887** [comment]
@namra4122 it's already assinged you can  take another issues .
all the best
