### ISSUE TITLE
Clicking on city name takes to the 'StartActivity' & No back button

### ISSUE THREAD

**Issue by PranavVyas20** [IEEE-VIT/weatherbes-android#37]
Currently there is no back button that takes the user to the 'StartActivity' but instead clicking on the city name in the MainActivity takes to the 'StartActivty' , I want to fix this bug and implement a back button for the purpose, can you assign me to this please

Here is th video reproducing the issue:
https://user-images.githubusercontent.com/90063033/135728841-10b9b0d4-bf88-4327-92ad-4991bf639c9f.mp4

**Comment by Archita01** [comment]
Hey @PranavVyas20, I have assigned the issue to you. You can make the required changes.

**Comment by PranavVyas20** [comment]
The issue is fixed , it can be closed now
