### ISSUE TITLE
Replace First screen after Splash with Current location Weather

### ISSUE THREAD

**Issue by rohanbabbar04** [IEEE-VIT/weatherbes-android#38]
The first screen should display the weather of the current location of the user with an option to go to the search city name screen.

If you want this enhancement then I would like to work on it

**Comment by jazxii** [comment]
hey @rohanbabbar04 , sorry but we already have a similar issue below at #4. please check it and comment there to get assigned. Thanks!

**Comment by rohanbabbar04** [comment]
Sorry didn't notice that
