### ISSUE TITLE
No city found for random city inputs

### ISSUE THREAD

**Issue by Archita01** [IEEE-VIT/weatherbes-android#6]

**Comment by pranatimittal** [comment]
what exactly needs to be done in this issue? an alert for random city inputs saying 'city doesn't exist'?

**Comment by Jatin887** [comment]
@pranatimittal yes, you can genrate a toast . 'city not found'

**Comment by Archita01** [comment]
@pranatimittal yes, a toast can be generated saying that the city does not exist.

**Comment by iamyajat** [comment]
@Archita01, can I take this issue up?

**Comment by iamyajat** [comment]
Can I pick this issue up?

**Comment by avikkundu** [comment]
want to work on it.

**Comment by Archita01** [comment]
Cool I have assigned it to you @avikkundu. All the best!

**Comment by pranatimittal** [comment]
@Archita01 Hey, I know you have assigned to other person but I enquired bcz I was interested. Is it possible you could change?

**Comment by jazxii** [comment]
hey @pranatimittal , Sorry, as you didn't reply in time, we didn't know that you were interested in picking it up. So we assigned it to someone else

**Comment by pranatimittal** [comment]
@jazxii No worries, i will see if I can contribute to any other issue. Happy to help out with solution thinking

**Comment by Positron007** [comment]
Hey can you please assign this to me? I want to work on it.

**Comment by jazxii** [comment]
Hey @Positron007, Sorry but we have already assigned this to someone else. Please checkout our other open issues. Good Luck!

**Comment by Ishan-001** [comment]
@Positron007 @pranatimittal you can create a pull request if you want. We'll not merge it but mark it as 'hacktoberfest-accepted' if it's valid.

**Comment by avikkundu** [comment]
i have created a pull request
