### ISSUE TITLE
Day should be mentioned

### ISSUE THREAD

**Issue by Archita01** [IEEE-VIT/weatherbes-android#8]

**Comment by UbadahJ** [comment]
@Archita01 Can you elaborate on where you want this? Preferably with a screenshot

**Comment by Archita01** [comment]
@UbadahJ It should be preferably mentioned beside the date.

**Comment by UbadahJ** [comment]
@Archita01 assign me

**Comment by UbadahJ** [comment]
Add day alongside the current date

![image](https://user-images.githubusercontent.com/26687928/135713412-a4cba4e5-5c78-4117-a1cc-73a29288bd99.png)

**Comment by Jatin887** [comment]
@UbadahJ All the best
